If you're not able to install R and RStudio on your laptop, you can access RStudio through a web browser.

You'll be using RStudio through a front-end interface called Jupyter that will manage starting RStudio.

0) You need to be logged into AirBears2 or EduRoam wireless. You cannot use CalVisitor. To use AirBears2 based on your CalNet ID, see the instructions at the bottom before proceeding to the next step.

1) Go to https://datahub.berkeley.edu/user-redirect/rstudio

2) Use your CalNet credentials to login.

3) At this point, to make the bootcamp materials accessible to your RStudio session, you'll need to do the following:

Within RStudio go to File->New Project->Version Control->Git and enter:

- "Repository URL": https://github.com/berkeley-scf/r-bootcamp-fall-2019
- "Project Directory Name": r-bootcamp-fall-2019 (or something else of your choosing)
- "Directory": ~

Then to update from the repository to get any changes we've made, you can select (from within RStudio):
Tools->Version Control->Pull Branches

or from the Environment/History/Git window, click on the Git tab and then on the blue down arrow.

6) To restart RStudio (e.g., if you're having a problem with R), click on the orange power button in the upper right.

7) To end your session entirely, just kill the browser or browser tab.

### AirBears2 Access

Please follow these instructions if you are trying to access AirBears2 if you have never accessed AirBears2 before.

1) Go to [https://idc.berkeley.edu/mmk](https://idc.berkeley.edu/mmk) and click on "Login via CalNet".

2) Login with your CalNet credentials and choose "AirBears2".

3) Select "Set Key" and follow the instructions.

4) Use the key that is generated to logon to the AirBears2 wireless network. 
